name: Build

on: [push, pull_request]

env:
  CIBW_BEFORE_BUILD_LINUX: curl -sSf https://sh.rustup.rs | sh -s -- -y
  CIBW_ENVIRONMENT_LINUX: "PATH=$HOME/.cargo/bin:$PATH"
  CIBW_SKIP: "cp36-* cp37-* cp38-* pp* *-win32 *-musllinux* *_i686"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.22.0

      - name: Install Cygwin
        uses: cygwin/cygwin-install-action@v4
        with:
          packages: >
            gcc-g++
            ghostscript
            git
            ImageMagick
            jpeg
            libfreetype-devel
            libimagequant-devel
            libjpeg-devel
            liblapack-devel
            liblcms2-devel
            libopenjp2-devel
            libraqm-devel
            libtiff-devel
            libwebp-devel
            libxcb-devel
            libxcb-xinerama0
            make
            netpbm
            perl
            python3${{ matrix.python-minor-version }}-cython
            python3${{ matrix.python-minor-version }}-devel
            python3${{ matrix.python-minor-version }}-ipython
            python3${{ matrix.python-minor-version }}-numpy
            python3${{ matrix.python-minor-version }}-sip
            python3${{ matrix.python-minor-version }}-tkinter
            wget
            xorg-server-extra
            zlib-devel

      - name: Add Lapack to PATH
        uses: egor-tensin/cleanup-path@v4
        with:
          dirs: 'C:\cygwin\bin;C:\cygwin\lib\lapack'

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl